apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: example-validating-webhook-configuration
webhooks:
  - name: example-webhook
    clientConfig:
      service:
        name: example-webhook-service
        namespace: example-namespace
        path: /mutate
      caBundle: "CA_BUNDLE"
    rules:
      - apiGroups:
          - ""
          - apps
        apiVersions:
          - v1
          - apps/v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - deployments
          - replicasets
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]